SPOOL PENDINGRPT.TXT;
 SELECT CT.REC_COUNT
,CP.COMPANY_FULLNAME
,G.PARENT_COMPANY_ID
,C.COMPANY_FULLNAME
,CT.GROUP_ID
,G.GROUP_FULLNAME
,G.CM_CLAIMS
,(
     SELECT SUM(BALANCE)
       FROM CTS S
      WHERE S.CLAIM_STATUS_ID IN(732,731)
    AND S.GROUP_ID             = CT.GROUP_ID
  )
  BALANCE
,(
SELECT MAX(LOG_DATE)
       FROM CLAIM_LOG
      WHERE LOG_DATE > TRUNC(SYSDATE) - 1
    AND LOG_COMMENT LIKE 'Queueing up Claims Generation Message for Group%'
    AND GROUP_ID = CT.GROUP_ID
) LAST_LOG_DATE
   FROM
  (
     SELECT COUNT( *) REC_COUNT
    ,S.GROUP_ID
       FROM CTS S
      WHERE S.CLAIM_STATUS_ID IN(732,731)
   GROUP BY S.GROUP_ID
   ORDER BY REC_COUNT DESC
  )
  CT
INNER JOIN MAINT_GROUP G
     ON CT.GROUP_ID = G.GROUP_ID
INNER JOIN MAINT_PARENT_COMPANY C
     ON G.PARENT_COMPANY_ID = C.PARENT_COMPANY_ID
INNER JOIN MAINT_PARENT_COMPANY CP
     ON C.RESELLER_ID = CP.PARENT_COMPANY_ID
ORDER BY CT.REC_COUNT DESC;
SPOOL OFF;
